/*  =========================================================================
    frenchaccent - FRENCHACCENT wrapper

    Copyright (c) the Contributors as noted in the AUTHORS file.       
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
    =========================================================================
*/

#ifndef frenchaccent_library_H_INCLUDED
#define frenchaccent_library_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <zmq.h>
#include <czmq.h>

//  FRENCHACCENT version macros for compile-time API detection

#define FRENCHACCENT_VERSION_MAJOR 1
#define FRENCHACCENT_VERSION_MINOR 0
#define FRENCHACCENT_VERSION_PATCH 0

#define FRENCHACCENT_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define FRENCHACCENT_VERSION \
    FRENCHACCENT_MAKE_VERSION(FRENCHACCENT_VERSION_MAJOR, FRENCHACCENT_VERSION_MINOR, FRENCHACCENT_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined LIBFRENCHACCENT_STATIC
#       define FRENCHACCENT_EXPORT
#   elif defined LIBFRENCHACCENT_EXPORTS
#       define FRENCHACCENT_EXPORT __declspec(dllexport)
#   else
#       define FRENCHACCENT_EXPORT __declspec(dllimport)
#   endif
#else
#   define FRENCHACCENT_EXPORT
#endif

//  Opaque class structures to allow forward references
typedef struct _textconverter_t textconverter_t;
#define TEXTCONVERTER_T_DEFINED


//  Public API classes
#include "textconverter.h"

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Please refer to the README for information about making permanent changes.  #
################################################################################
*/
