/*  =========================================================================
    text - Converts text without accents.

    Copyright (c) the Contributors as noted in the AUTHORS file.       
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef TEXT_H_INCLUDED
#define TEXT_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/text.xml" to make changes.
//  @interface
//  Create a new text.
FRENCHACCENT_EXPORT text_t *
    text_new ();

//  Destroy the text.
FRENCHACCENT_EXPORT void
    text_destroy (text_t **self_p);

//  
FRENCHACCENT_EXPORT char *
    text_convert (text_t *self, char const *regex, char const *replace, const char *in);

//  Print properties of the text object.
FRENCHACCENT_EXPORT void
    text_print (text_t *self);

//  Self test of this class.
FRENCHACCENT_EXPORT void
    text_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
