/*  =========================================================================
    textconverter - Converts text without accents.

    Copyright (c) the Contributors as noted in the AUTHORS file.       
                                                                       
    This Source Code Form is subject to the terms of the Mozilla Public
    License, v. 2.0. If a copy of the MPL was not distributed with this
    file, You can obtain one at http://mozilla.org/MPL/2.0/.           
    =========================================================================
*/

#ifndef TEXTCONVERTER_H_INCLUDED
#define TEXTCONVERTER_H_INCLUDED

#ifdef __cplusplus
extern "C" {
#endif


//  @warning THE FOLLOWING @INTERFACE BLOCK IS AUTO-GENERATED BY ZPROJECT!
//  @warning Please edit the model at "api/textconverter.xml" to make changes.
//  @interface
//  Create a new textconverter.
FRENCHACCENT_EXPORT textconverter_t *
    textconverter_new ();

//  Destroy the textconverter.
FRENCHACCENT_EXPORT void
    textconverter_destroy (textconverter_t **self_p);

//  
FRENCHACCENT_EXPORT char *
    textconverter_convert (textconverter_t *self, char const *regex, char const *replace, const char *in);

//  Print properties of the textconverter object.
FRENCHACCENT_EXPORT void
    textconverter_print (textconverter_t *self);

//  Self test of this class.
FRENCHACCENT_EXPORT void
    textconverter_test (bool verbose);
//  @end

#ifdef __cplusplus
}
#endif

#endif
